# Generated by Django 3.0.8 on 2020-08-05 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slider_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
