# Generated by Django 3.0.8 on 2020-08-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_slider_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slider_content',
            new_name='slidercontent',
        ),
    ]
