# Generated by Django 3.0.8 on 2020-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200805_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
