# Generated by Django 3.0.8 on 2020-08-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpost_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='preview',
        ),
    ]
