# Generated by Django 3.0.8 on 2020-08-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200807_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='BlogPicture',
            new_name='Picture',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='mptt_level',
            new_name='level',
        ),
    ]
