# Generated by Django 3.0.8 on 2020-08-09 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_auto_20200809_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentFormMessage',
            new_name='Comment',
        ),
    ]
