# Generated by Django 3.0.8 on 2020-07-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200731_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
