# Generated by Django 3.0.8 on 2020-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='smtpport',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
