# Generated by Django 3.0.8 on 2020-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactformmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
