# Generated by Django 3.0.8 on 2020-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_setting_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
