# Generated by Django 3.0.8 on 2020-08-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_setting_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='contact',
            new_name='ourservice',
        ),
    ]
