# Generated by Django 3.0.8 on 2020-08-10 20:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200808_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='location',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
