# Generated by Django 3.0.8 on 2020-08-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='ourservice',
            new_name='ourprojects',
        ),
    ]
