# Generated by Django 3.0.8 on 2020-08-14 17:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200814_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ourservices',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
